version: '2.1'

services:

  # The Drone Delivery service, a J2E system
  ddsystem:
    image: livrair/dd-int
    container_name: ddsystem
    environment:
      - map_host=ddpartners
      - map_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - external_partners
    networks:
      - dd-network

  # The external partners, implemented as .Net services
  external_partners:
    image: livrair/dd-ext
    container_name: ddpartners
    expose:
      - "9090"
    ports:
      - "9090:9090"
    networks:
      - dd-network

networks:
  dd-network:
    driver: bridge